[package]
name = "quickjs-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
libc = "0.2.0"
near-sdk = "3.1.0"

[build-dependencies]
bindgen = "0.53.1"
