spin_manifest_version = 2

[application]
name = "ai-proxy"
version = "0.1.0"
authors = ["Peter Salomonsen <pjsalomonsen@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "ai-proxy"

[component.ai-proxy]
source = "ai-proxy/target/wasm32-wasip1/release/ai_proxy.wasm"
allowed_outbound_hosts = ["https://rpc.mainnet.fastnear.com:443", "https://api.openai.com:443", "https://*.openai.azure.com", "https://rpc.testnet.near.org:443", "https://rpc.mainnet.near.org:443", "http://localhost:14500", "http://127.0.0.1:3001"]
key_value_stores = ["default"]

[component.ai-proxy.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "ai-proxy"
watch = ["src/**/*.rs", "Cargo.toml"]

[variables]
api_key_method = { default = "authorization" }
api_key = { required = true }
ai_completions_endpoint = { default = "https://api.openai.com/v1/chat/completions" }
rpc_url = {required = true }

[component.ai-proxy.variables]
api_key_method = "{{ api_key_method }}"
api_key = "{{ api_key }}"
ai_completions_endpoint =  "{{ ai_completions_endpoint }}"
rpc_url = "{{ rpc_url }}"

[component.ai-proxy.tool.spin-test]
source = "tests/target/wasm32-wasip1/release/tests.wasm"
build = "cargo component build --release"
workdir = "tests"
